marks=[]                      
f1=input("Enter your marks:")
marks.append(f1)
f2=input("Enter your marks:")
marks.append(f2)
f3=input("Enter your marks:")
marks.append(f3)
f4=input("Enter your marks:")
marks.append(f4)
f5=input("Enter your marks:")
marks.append(f5)
f6=input("Enter your marks:")
marks.append(f6)
f7=input("Enter your marks:")
marks.append(f7)
marks.sort()# this sorts your output in aranging order 
print("Your marks in ascending order are ",(marks))