marks=[]                      
f1=int(input("Enter your marks in numeric form:"))
marks.append(f1)
f2=int(input("Enter your marks in numeric form:"))
marks.append(f2)
f3=int(input("Enter your marks in numeric form:"))
marks.append(f3)
f4=int(input("Enter your marks in numeric form:"))
marks.append(f4)
f5=int(input("Enter your marks in numeric form:"))
marks.append(f5)
f6=int(input("Enter your marks in numeric form:"))
marks.append(f6)
f7=int(input("Enter your marks in numeric form:"))
marks.append(f7)
marks.sort()# this sorts your output in aranging order 
print("Your marks in ascending order are ",(marks))
